# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c76cf199b3e60cb30c5c26630a6fb6ef2f8c64ca9d6fb70a4b005624d925ec15f015f86006360c54d47e139675f8a48a140126a73bc342f8c1833cd73b4a708

test:
  secret_key_base: b354b4b8530cd97529658f18344d2697f244a5c1d2a38590e6655db1f031f46d93a6c6118ccf6ec2ab1c7d0a6e93334cf43e0be36b01ee12637facbe065fe679

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
